apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-contact-worker
  namespace: tc3
  labels:
    app: create-contact-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-contact-worker
  template:
    metadata:
      labels:
        app: create-contact-worker
    spec:
      containers:
      - name: create-contact-worker
        image: fiaptech3acr.azurecr.io/tc3-create-contact-worker:latest
        ports:
        - containerPort: 8091
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: create-contact-worker-service
  namespace: tc3
spec:
  selector:
    app: create-contact-worker
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP