apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-contact-worker
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: create-contact-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-contact-worker
  template:
    metadata:
      labels:
        app: create-contact-worker
    spec:
      containers:
      - name: create-contact-worker
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        ports:
        - containerPort: 8091
        livenessProbe:
          httpGet:
            path: /
            port: 8091
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        resources:
          cpu: 1m
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: create-contact-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: create-contact-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: create-contact-worker-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: create-contact-worker
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP